export const pageConstants = {
  pageTitle: "Income Statement",
  gameBatch: "Game Batch",
  gameTeam: "Game Team",
  tableHeading: [
    "Line_no",
    "Details",
    "PrvYear_End",
    "Period_1",
    "Period_2",
    "Period_3",
    "Period_4",
    "Period_5",
    "Period_6",
    "Period_7",
    "Period_8",
    "Period_9",
    "Period_10",
    "Period_11",
    "Period_12",
  ],
};
