/*
export const pageConstants = {
  gameBatch: "Batch",
  gameTeam: "Team",
  tableHeading: [
    "Line_no",
    "Details",
    "PrvYear_End",
    "Period_1",
    "Period_2",
    "Period_3",
    "Period_4",
    "Period_5",
    "Period_6",
    "Period_7",
    "Period_8",
    "Period_9",
    "Period_10",
    "Period_11",
    "Period_12",
  ],
};
*/
export const pageConstants = {
  gameBatch: "Batch",
  gameTeam: "Team",
  tableHeading: [
    "Line_no",
    "Details",
    "PrvYear_End",
    "Period_1",
    "Period_2",
    "Period_3",
    "Period_4",
    "Period_5",
    "Period_6",
    "Period_7",
    "Period_8",
    "Period_9",
    "Period_10",
    "Period_11",
    "Period_12",
  ],
  vitalRows: [
    "Sales Revenue",
    "Cost of Goods Sold",
    "Gross_Margin",
    "Operating OH Cost",
    "Operating Profit",
    "Admin OH Expense",
    "Non-Project Expense",
    "Profit Before Int & Tax",
    "Profit Before Tax",
    "Profit After Tax",
    "Profit %",
  ],
};
