export const pageConstants = {
  gameBatch: "Batch",
  gameTeam: "Team",
  tableHeading: [
    "Line_no",
    "Details",
    "PrvYear_End",
    "Period_1",
    "Period_2",
    "Period_3",
    "Period_4",
    "Period_5",
    "Period_6",
    "Period_7",
    "Period_8",
    "Period_9",
    "Period_10",
    "Period_11",
    "Period_12",
  ],
  vitalRows: [
    "Net Cash Flow from Operation",
    "Net Cash Inflow from Investing Activities",
    "Net Cash Inflow from Financing Activities",
    "Net Cash Flow from Operation,Investing & Financing",
    "Cash Balance at the beginning of the period",
    "Cash Balance at the End of the period",
  ],
};
