export const pageConstants = {
  pageTitle: "Operational Decision Input",
  gameBatch: "Game Batch",
  gameTeam: "Game Team",
  contentSection: {
    addBtnLabel: "Add",
    modifyBtnLabel: "Modify",
    saveBtnLabel: "Save",
    cancelBtnLabel: "Cancel",
    tableHeading: [
      "Description",
      "UOM",
      "Quantity",
      "Operation Info",
      "Unit Price",
      "currency",
      "Info Price",
    ],
    tableHeadingForAdd: [
      "Description",
      "Quantity",
      "Operation Info",
      "Unit Price",
      "Info Price",
    ],
    hiddenTableColumns: ["Part", "Qty_Id", "Period", "Price_Id"],
    hiddenTableColumnsForAdd: [
      "Qty_Id",
      "UOM",
      "Part",
      "Operation Info",
      "Period",
      "currency",
      "Price_Id",
    ],
    inputTypes: [
      { columnName: "Description", inputType: null },
      { columnName: "UOM", inputType: null },
      { columnName: "Quantity", inputType: "text" },
      { columnName: "Operation_Info", inputType: null },
      { columnName: "Unit_Price", inputType: "text" },
      { columnName: "currency", inputType: null },
      { columnName: "Info_Price", inputType: null },
    ],
    inputTypesForAdd: [
      { columnName: "Description", inputType: "select" },
      { columnName: "Quantity", inputType: "text" },
      { columnName: "Unit_Price", inputType: "text" },
      { columnName: "Info_Price", inputType: "select" },
    ],
  },
};
