export const pageConstants = {
  contentSection: {
    addBtnLabel: "Add",
    modifyBtnLabel: "Modify",
    saveBtnLabel: "Save",
    cancelBtnLabel: "Cancel",
    tableHeading: [
      "Item Description",
      "UOM",
      "Quantity",
      "Info_Qty",
      "Unit Price",
      "currency",
      "Info Price",
    ],
    tableHeadingForAdd: [
      "Item Description",
      "Quantity",
      "Info_Qty",
      "Unit Price",
      "Info Price",
    ],
    hiddenTableColumns: ["Qty_Id", "Part", "Period", "Price_Id"],
    hiddenTableColumnsForAdd: [
      "Qty_Id",
      "UOM",
      "Part",
      "Period",
      "currency",
      "Price_Id",
    ],
    inputTypes: [
      { columnName: "Item_Description", inputType: null },
      { columnName: "UOM", inputType: null },
      { columnName: "Quantity", inputType: "number" },
      { columnName: "Info_Qty", inputType: null },
      { columnName: "Unit_Price", inputType: "number" },
      { columnName: "currency", inputType: null },
      { columnName: "Info_Price", inputType: null },
    ],
    inputTypesForAdd: [
      { columnName: "Item_Description", inputType: "select" },
      { columnName: "Quantity", inputType: "number" },
      { columnName: "Info_Qty", inputType: "select" },
      { columnName: "Unit_Price", inputType: "number" },
      { columnName: "Info_Price", inputType: "select" },
    ],
  },
};
